### ISSUE TITLE
Take interface doesn’t work for limiting based on request contents

### ISSUE THREAD

**Issue by philips** [sethvargo/go-limiter#11]
Thanks for the library. I tried to use it in a project and the API is too limited for my application.

In my app I have a setup where I can let clients make unlimited number of requests if they provide a correct challenge key. But, if they fail to provide the correct key I need them to be limited for some duration.

In practice this means I have something like:

```

// calling validKey below is expensive so check if the client is rate limited first
_, _, _, ok := store.State 
if !ok {
  return 429
}

if !validKey(key) {
  _, _, _, ok := store.Take()
  if !ok {
    return 429
  }
}

doAppWork()
```

So, I would love to have the Store interface be extended to have a function such as `State` below:

```
	// State returns the current status of the limiter for the given key:
	//
	// - the configured limit size
	// - the number of remaining tokens in the interval
	// - the server time when new tokens will be available
	// - whether the take was successful
	//
	// If "ok" is false, the take was unsuccessful and the caller should NOT
	// service the request.
	//
	// See the note about keys on the interface documentation.
	State(key string) (limit, remaining, reset uint64, ok bool)
```

**Comment by sethvargo** [comment]
So you want a `Peek` operation that doesn't actually take?

**Comment by philips** [comment]
@sethvargo Yes! Peek.

**Comment by philips** [comment]
Would you be interested in a PR to implement this?

**Comment by sethvargo** [comment]
Sure! I probably wont have time to do it myself for a few weeks.
