### ISSUE TITLE
How to use Store from redisstore on httplimit.NewMiddleware ?

### ISSUE THREAD

**Issue by FRHuda** [sethvargo/go-limiter#17]
i need to create middleware from `httplimit.NewMiddleware` . but its func can't take `store` from `redisstore.New` because `redisstore.New` return `store` , not `storeWithContext`.

it happen in
```
github.com/sethvargo/go-limiter v0.4.1
github.com/sethvargo/go-redisstore v0.1.2
```

but i can use redisstore for `httplimit.NewMiddleware` in older version.

**Comment by sethvargo** [comment]
There's a runtime type assertion, so you can do something like `store.(limiter.StoreWithContext)`

**Comment by sethvargo** [comment]
Or wait for https://github.com/sethvargo/go-redisstore/pull/5 to merge and release.

**Comment by sethvargo** [comment]
v0.1.3
