### ISSUE TITLE
Disabling HTTP headers

### ISSUE THREAD

**Issue by eyalch** [sethvargo/go-limiter#24]
I understand the benefit of the various HTTP headers which are being added when using the middleware, but what if I'm not developing an API and just want to prevent a brute-force attack? Should I still be sending the rate-limiting HTTP headers?

If not, should we have an option to disable these headers? Potentially via a new parameter for `NewMiddleware`?

**Comment by sethvargo** [comment]
In that case, you're probably better off writing your own middleware that's a few LOC. If you take a look at the source for the middleware and remove the headers:

		// Take from the store.
		limit, remaining, reset, ok, err := m.store.Take(ctx, key)
		if err != nil {
			http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
			return
		}

		// Fail if there were no tokens remaining.
		if !ok {
			w.Header().Set(HeaderRetryAfter, resetTime)
			http.Error(w, http.StatusText(http.StatusTooManyRequests), http.StatusTooManyRequests)
			return
		}
