### ISSUE TITLE
Consider name memorystore

### ISSUE THREAD

**Issue by ahmetb** [sethvargo/go-limiter#3]
Package memorystore is confusing to GCP users probably since https://cloud.google.com/memorystore. inmemorystore is probably a better name to consider early on?

**Comment by sethvargo** [comment]
Hmm yea. There was a lot of refactoring and this is where it landed. It looks like there's no memorystore package - it's [redis](https://pkg.go.dev/cloud.google.com/go/redis/apiv1?tab=doc). Grumble there's not any easy way to alias a package name in Go.
