### ISSUE TITLE
Allow custom headers names

### ISSUE THREAD

**Issue by dmytrohridin** [sethvargo/go-limiter#33]
https://datatracker.ietf.org/doc/html/rfc6648

Can you introduce the possibility of customizing response header names (except for HeaderRetryAfter, since it's part of 429 response)?
This change can be done without any breaking changes to existing behavior. If you will approve - I can take to implement this one.

**Comment by sethvargo** [comment]
Hi @dmytrohridin - same response as https://github.com/sethvargo/go-limiter/issues/34#issuecomment-1121625596. I think it'd be best to write your own logic here. The middleware isn't supposed to satisfy every possible use case, just the most generic ones.
