### ISSUE TITLE
Allow custom response on 429

### ISSUE THREAD

**Issue by dmytrohridin** [sethvargo/go-limiter#34]
https://datatracker.ietf.org/doc/html/rfc7807
Allow introducing custom response behavior for 429 status code, Problem Details as an example.
Should not bring breaking changes, just will introduce new config param

**Comment by sethvargo** [comment]
Hi @dmytrohridin 

I assume you're talking about the `httplimit` package specifically? For custom behavior, my general recommendation is to build your own middleware. The existing logic isn't particularly complex: https://github.com/sethvargo/go-limiter/blob/67fff5ee8978ea6218af4d1354bb842096a5b543/httplimit/middleware.go#L91-L127

Then you can set your own headers, responses, or even custom logic.
