### ISSUE TITLE
By pass rate limiter by header

### ISSUE THREAD

**Issue by acbeni** [sethvargo/go-limiter#37]
Is it possible to bypass the rate limiter by some custom header? or maybe a custom bypasser function?

Sorry if the question was asked before, i just couldn't find much,

**Comment by sethvargo** [comment]
That seems like it could be easily abused. If you really wanted to do that, you could define a [custom key func](https://github.com/sethvargo/go-limiter/blob/67fff5ee8978ea6218af4d1354bb842096a5b543/httplimit/middleware.go#L38) that, when the debug header is present, generates a random string for the key. That would effectively bypass the rate limit for requests with that header.

**Comment by acbeni** [comment]
Thank you @sethvargo the solution you proposed would solve my issue, and thanks again for the nice framework and quick response ❤️
