### ISSUE TITLE
Take many tokens

### ISSUE THREAD

**Issue by FZambia** [sethvargo/go-limiter#38]
Hello, many thanks for the library with a great performance and nice API.

It's written in readme that:

> While go-limit supports rate limiting at the HTTP layer, it can also be used to rate limit literally anything.

I am researching a rate limiting based on traffic read from the socket. In this case I need to take the number of tokens which is equal to the length of data read from the socket. It seems not possible with the current package API. Is it good idea to extend API in this way or it's out of scope?

**Comment by sethvargo** [comment]
Hi @FZambia - the library is hyper optimized for taking a single entry from a leaky bucket. If you want to take multiple items from a bucket, I would recommend looking at a different library, including the [one in x](https://pkg.go.dev/golang.org/x/time/rate).

**Comment by FZambia** [comment]
I see, thank you
