### ISSUE TITLE
Out of date comment?

### ISSUE THREAD

**Issue by carlpett** [sethvargo/go-limiter#4]
Hey,
Thanks for publishing this! Currently reading through the code, and snagged on this comment:
https://github.com/sethvargo/go-limiter/blob/633a6c152623862c31f939b19fcff13606de2222/memorystore/store.go#L142-L146

While `b.take()` will return true, the comment is a bit confusing. I suspect it was written before that call was put in, I guess to avoid having an extra parameter to `newBucket` with "initial tokens"?

**Comment by sethvargo** [comment]
Oh yea, that's outdated. The original implementation didn't include "buckets".
