### ISSUE TITLE
Calling back the server time can cause an exception in the flow limiting mechanism

### ISSUE THREAD

**Issue by yujiangjiang** [sethvargo/go-limiter#41]
![image](https://github.com/sethvargo/go-limiter/assets/15154648/451cf7e0-be8e-445a-bb85-68a2d27468ba)
If the server time is adjusted to a previous time, the condition 'b. lastTick<currTick' will not occur, and 'b. availabilityTokens' will quickly drop to 0, and subsequent requests will be restricted from accessing

**Comment by sethvargo** [comment]
Pull Requests are welcome!
