### ISSUE TITLE
Limiting by Number Of Keys

### ISSUE THREAD

**Issue by sundarv85** [sethvargo/go-limiter#48]
The limit of tokens per key is handled by go-limiter. Additionally I would like to also limit by the max number of keys itself. Is there an existing function for the same?

If not, could you expose the NumOfKeys() or Size() function as well from the Store?

**Comment by sethvargo** [comment]
Hi @sundarv85 - thank you for opening an issue. I largely consider this package and its API surface to be complete. If you'd like additional functionality, I recommend you fork and maintain your own copy. Thanks!
