### ISSUE TITLE
How to Interpret 'reset'

### ISSUE THREAD

**Issue by alexanderbez** [sethvargo/go-limiter#5]
I noticed this library uses the `fasttime` package which uses `runtime.nanotime`. I'm having difficulty interpreting the value of `reset` returned by the `Take` API. For instance, looking at the HTTP middleware, you'll see a value like `Sun, 04 Jan 1970 01:55:37 UTC`, whereas I'd expect to see a value that is roughly greater than the time the request was executed.

Should reset be interpreted as nanoseconds until replenishment from _now_? If so, https://github.com/sethvargo/go-limiter/blob/main/httplimit/middleware.go#L102 doesn't seem correct.

```go
func TestNow(t *testing.T) {
	n1 := Now()
	n2 := time.Now().UnixNano()

	fmt.Printf("fasttime: %d\n", n1)
	fmt.Printf("time.Now(): %d\n", n2)

	t1 := time.Unix(0, int64(n1)).UTC().Format(time.RFC1123)
	t2 := time.Unix(0, n2).UTC().Format(time.RFC1123)
	require.Equal(t, t1, t2)
}
```

```
=== RUN   TestNow
fasttime: 268633347645075
time.Now(): 1595538425892185000
    TestNow: fasttime_test.go:20: 
        	Error Trace:	fasttime_test.go:20
        	Error:      	Not equal: 
        	            	expected: "Sun, 04 Jan 1970 02:37:13 UTC"
        	            	actual  : "Thu, 23 Jul 2020 21:07:05 UTC"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-Sun, 04 Jan 1970 02:37:13 UTC
        	            	+Thu, 23 Jul 2020 21:07:05 UTC
        	Test:       	TestNow
--- FAIL: TestNow (0.00s)
```

**Comment by sethvargo** [comment]
No, it should be unix epoch time in nanoseconds.

**Comment by alexanderbez** [comment]
If it's UNIX epoch in nanoseconds then why is `t1` (now) formatted `Sun, 04 Jan 1970 02:37:13 UTC`?
